# Generated by Django 5.0.4 on 2024-05-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('telephone', models.IntegerField(max_length=12)),
                ('amount', models.IntegerField(max_length=6)),
                ('payment', models.CharField(max_length=50)),
            ],
        ),
    ]
