# Generated by Django 5.0.4 on 2024-05-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='amount',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='payment',
            new_name='Payment_Options',
        ),
    ]
