# Generated by Django 5.0.4 on 2024-05-16 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0005_event_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Perfomance_Type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='EcoApp.event'),
        ),
    ]
