# Generated by Django 5.0.4 on 2024-05-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0007_alter_booking_perfomance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Perfomance_Type',
        ),
        migrations.AddField(
            model_name='booking',
            name='Performance_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EcoApp.event'),
        ),
    ]
