# Generated by Django 5.0.4 on 2024-05-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0009_remove_booking_performance_type_alter_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Performance_Type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Amount',
            field=models.IntegerField(max_length=6),
        ),
    ]
