# Generated by Django 5.0.4 on 2024-05-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0011_alter_booking_performance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Performance_Type',
        ),
    ]
