# Generated by Django 5.0.4 on 2024-05-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0013_booking_performance_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Performance_Type',
            new_name='event',
        ),
    ]
