# Generated by Django 5.0.4 on 2024-05-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0014_rename_performance_type_booking_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Amount',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='booking',
            name='telephone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='telephone_number',
            field=models.CharField(max_length=12),
        ),
    ]
