# Generated by Django 5.0.4 on 2024-05-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0015_alter_booking_amount_alter_booking_telephone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Hours',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
