# Generated by Django 5.0.4 on 2024-05-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0016_remove_booking_event_event_date_event_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
