# Generated by Django 5.0.4 on 2024-05-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0017_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=12)),
                ('Amount', models.CharField(max_length=6)),
                ('Payment_Options', models.CharField(max_length=50)),
            ],
        ),
    ]
